# Generated by Django 4.2.18 on 2025-12-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onehub_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='address',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reg',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
