# Generated by Django 4.2.18 on 2025-12-05 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onehub_app', '0002_reg_address_reg_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reg',
            new_name='User',
        ),
    ]
